global using System.Diagnostics.CodeAnalysis;
global using Marketplace.UI.Core.Constants;
global using Marketplace.UI.Core.Models;
global using Marketplace.UI.Core.Models.Configurations;
global using Marketplace.UI.Core.Models.Requests.Catalog;
global using Marketplace.UI.Core.Models.Responses.Catalog;
global using Marketplace.UI.Core.Models.ViewModels.Catalog;
global using Marketplace.UI.Core.Services.Interfaces;
global using Microsoft.Extensions.Options;